### ISSUE TITLE
BufferUnderflowException is thrown if UserFlags D and/or H in KerbValidationInfo are set, but the actual pointers are NULL

### ISSUE THREAD

**Issue by michael-o** [michael-o/tomcatspnegoad#23]
The following exception can be observed:
```
2024-09-29T16:21:23.581 SCHWERWIEGEND [https-openssl-apr-8444-exec-29] org.apache.catalina.core.StandardHostValve.invoke Exception Processing [/foo]
    java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:532)
        at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:366)
        at net.sf.michaelo.tomcat.pac.PacDataBuffer.getUnsignedInt(PacDataBuffer.java:84)
        at net.sf.michaelo.tomcat.pac.KerbValidationInfo.<init>(KerbValidationInfo.java:231)
        at net.sf.michaelo.tomcat.pac.Pac.<init>(Pac.java:147)
        at net.sf.michaelo.tomcat.realm.PacDataActiveDirectoryRealm.getPrincipal(PacDataActiveDirectoryRealm.java:157)
        at org.apache.catalina.realm.RealmBase.authenticate(RealmBase.java:495)
        at net.sf.michaelo.tomcat.authenticator.SpnegoAuthenticator.doAuthenticate(SpnegoAuthenticator.java:158)
```

It turns out that in some cases (which are unclear) `extraSidsPointer` is 0 (`NULL`), but EXTRA_SIDS_USER_FLAG (flag D) is set in `UserFlags`. We need extra checks here.

**Comment by michael-o** [comment]
The actual issue should not happen IMHO. If you look at https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-pac/69e86ccc-85e3-41b9-b514-7d969cd0ed73 it is expected that if the flags are set the pointers should not be `NULL`. At least Samba's code makes it sure:
* https://github.com/samba-team/samba/blob/f749330ddaba04cdae20570a9e842327715f3594/auth/auth_sam_reply.c#L399-L404
* https://github.com/samba-team/samba/blob/f749330ddaba04cdae20570a9e842327715f3594/python/samba/tests/krb5/raw_testcase.py#L4195-L4214

Will inquire with the Samba team for their opinion.

**Comment by michael-o** [comment]
This is sets the flag no matter what: https://github.com/samba-team/samba/blob/f749330ddaba04cdae20570a9e842327715f3594/source3/auth/server_info.c#L599-L613
